project:
  type: manuscript

format:
  html:
    toc: true
  docx:
    default: true
    level: 2
  pdf:
    default: true


website:
  back-to-top-navigation: true
  page-footer:

    left: "Copyright 2025, Paolo Volterra"  
    right: 
      - icon: github
        href: https://paolovolterra.github.io
      - icon: twitter 
        href: https://twitter.com/ghibbli