project:
  type: website
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600
  output-dir: docs


website:
  site-url: https://paolovolterra.github.io
  repo-url: https://github.com/paolovolterra/paolovolterra.github.io
  title: "Paolo Volterra's website"
  page-navigation: true
  back-to-top-navigation: true
  twitter-card:
    creator: "@ghibbli"
  repo-actions: [edit, issue]

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - text: "Books"
        menu:
          - text: "Test1"
            href: https://quarto.org/docs/books/
          - text: "Test2"
            href: https://quarto.org/docs/books/

    title: "Paolo Volterra's website"

format:
  html:
    css: MCC.css
    toc: true
    theme:
      - pulse
      - BeatrizMilz.scss

freeze: true