project:
  type: website
  output-dir: docs

publish:
  branch: main
  message: "Aggiornamento sito generato con Quarto"

website:
  site-url: https://paolovolterra.github.io
  title: "Paolo Volterra's website"
  page-navigation: true
  back-to-top-navigation: true
  twitter-card:
    creator: "@ghibbli"
  repo-actions: [edit, issue]

  navbar:
    background: "#007a53"
    search: true
    title: "Paolo Volterra's website"
    right:
      - href: index.qmd
        text: Home
      - posts.qmd
  repo-url: https://github.com/paolovolterra/paolovolterra.github.io

  page-footer:
    left: "Costruito con [quarto](https://quarto.org) 😍 | Contenuti in [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.it)"
    right:
      - icon: twitter
        href: https://twitter.com/@ghibbli
      - icon: github
        href: https://github.com/paolovolterra/paolovolterra.github.io

format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - styles.scss
    mainfont: Nunito
    toc: true