project:
  type: website
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600
  output-dir: docs


website:
  site-url: https://paolovolterra.github.io
  repo-url: https://github.com/paolovolterra/paolovolterra.github.io
  title: "Paolo Volterra's website"
  page-navigation: true
  back-to-top-navigation: true
  twitter-card:
    creator: "@ghibbli"
  repo-actions: [edit, issue]

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - text: "Books"
        menu:
          - text: "Test1"
            href: https://quarto.org/docs/books/
          - text: "Test2"
            href: https://quarto.org/docs/books/

    title: "Paolo Volterra's website"

    right:
      - icon: rss
        aria-label: rss
        href: https://github.com/paolovolterra
      - icon: github
        aria-label: GitHub
        href: https://github.com/paolovolterra
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/paolo-volterra-08596b6
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/ghibbli
      - text: "<i class='fa-brands fa-bluesky'></i>"
        href: https://bsky.app/profile/ghibbli.bsky.social


format:
  html:
    css: MCC.css
    toc: true
    theme:
      - pulse
      - BeatrizMilz.scss

page-footer:
  border: true
  left: "&#169; 2025 Paolo Volterra"
  right: "fatto con ︎♥️ & [Quarto](https://quarto.org)"

freeze: false