project:
  type: website
  preview:
    port: 3434
    browser: true
    watch-inputs: true
    timeout: 3600
  output-dir: docs


website:
  site-url: https://paolovolterra.github.io
  repo-url: https://github.com/paolovolterra/paolovolterra.github.io
  title: "Paolo Volterra's website"
  page-navigation: true
  back-to-top-navigation: true
  twitter-card:
    creator: "@ghibbli"
  repo-actions: [edit, issue]

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts

    title: "Paolo Volterra's website"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
