---
pagetitle: "Paolo Volterra | About"
title: "_Impara l'arte e mettila da parte_"
subtitle: "un data scientist ... al contrario"

about:
  id: hero-heading
  template: jolla

  links:
    - icon: github
      text: GitHub
      href: https://github.com/ghibbli
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/paolo-volterra-08596b6/
toc: false
anchor-sections: false
execute: 
  freeze: auto
---

::: {#hero-heading}
:::


Anno nuovo, vita nuova

Col 2025 riprendo a scrivere il mio blog, iniziato in R durante il covid

Motivo?

Primo: gratitudine per tanti filantropi che gratuitamente hanno messo online nel tempo tante informazioni che mi hanno permesso di progredire

Secondo: dove ti giri, gli esempi sono basati sugli stessi dati (Titanic, Boston, carte di credito, iris, cancer...). Voglio andare oltre il copia/incolla

Terzo: gli esempi sono sempre basati su dati retail, mentre nessuno spiega usando dati imprese (più difficili da trovare, anche perchè vanno acquistati)
Userò quindi gli #opendata

Quarto: molte persono desistono dall'approfondire tecnicalities che richiedono tempo e voglia per essere trovate, capite e applicate
Se penso a quanto tempo ho dedicato ad evolvere ... ( e poi tutta questa mia conoscenza/esperienza andrà persa, prima o poi)

Perchè un data scientist al contrario?

Sono laureato in economia, master in marketing
Non sono partito dalla formazione che può avere uno statistico od un ingegnere che poi le deve applicare nel lavoro in un campo magari ostico al suo interesse

Ho una preparazione economica che ho voluto potenziare con soluzioni tecniche. Spesso vedo persone che si fermano se non hanno il dato pronto. Io me lo vado a costruire

Ogni tanto scriverò pensieri ad alta voce


> Quando hai dato lo stesso consiglio 3 volte, scrivi un post ([David Robinson](https://twitter.com/drob/status/928447584712253440))

